image: Visual Studio 2017
shallow_clone: true

init:
 - ps: Update-AppveyorBuild -Version "$(Get-Date $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -format yyyy-MM-dd).$($env:APPVEYOR_REPO_COMMIT.substring(0, 7))"
 - set PATH="%PATH%;C:\Program Files (x86)\WiX Toolset v3.11\bin"
 - echo %PATH%

install:
  - curl -fsSL -O http://prdownloads.sourceforge.net/scons/scons-local-2.5.1.zip
  - cinst imagemagick.tool
  - 7z x scons-local-2.5.1.zip -oscons
  - del /F scons-local-2.5.1.zip

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
  - python scons/scons.py platform=windows tools=yes target=release_debug verbose=no warnings=no
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x86
  - python scons/scons.py platform=windows tools=yes target=release_debug verbose=no warnings=no

after_build:
  - mkdir %APPVEYOR_BUILD_VERSION%
  - 7z a %APPVEYOR_BUILD_VERSION%\godot-windows-x86_64-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\godot.windows.opt.tools.64.exe
  - 7z a %APPVEYOR_BUILD_VERSION%\godot-windows-x86-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\godot.windows.opt.tools.32.exe
  - git clone https://github.com/tomuxmon/godot.msi
  - cd godot.msi
  - magick convert ..\icon.png -define icon:auto-resize=256,128,64,48,32,16 godot.ico
  - copy /Y ..\bin\godot.windows.opt.tools.64.exe godot.exe
  - candle godot.wxs -dexe_path=godot.exe -dversion=3.0.0.0
  - light godot.wixobj
  - move godot.msi ..\%APPVEYOR_BUILD_VERSION%\godot-windows-x86_64-%APPVEYOR_BUILD_VERSION%.msi
  - copy /Y ..\bin\godot.windows.opt.tools.32.exe godot.exe
  - candle godot.wxs -dexe_path=godot.exe -dversion=3.0.0.0
  - light godot.wixobj
  - move godot.msi ..\%APPVEYOR_BUILD_VERSION%\godot-windows-x86-%APPVEYOR_BUILD_VERSION%.msi

artifacts:
  - path: '**\*.zip'
  - path: '**\*.msi'

deploy:
  - provider: FTP
    protocol: sftp
    host: hugo.pro
    username: godot
    password:
      secure: wPzpdQRz589GAsHPwAXMTgLsUrDB2+n2m2dKvV6Wihc=
    folder: autobuild
    application:
    active_mode: false
    debug: true

  - provider: BinTray
    username: calinou
    api_key:
      secure: GJf+DF+dDdNyHsFP01JqBDaVUTI6jQ7VtDrDVp1S7vD94kT8/AbSOZSxIXyb7MBr
    subject: calinou
    repo: godot
    package: editor
    publish: true
    override: true
