image: Visual Studio 2017
shallow_clone: true

init:
 - ps: Update-AppveyorBuild -Version "3.0.0-dev_$(Get-Date -format yyyy-MM-dd)_$($env:APPVEYOR_REPO_COMMIT.substring(0, 7))"
 - echo %APPVEYOR_REPO_COMMIT_TIMESTAMP%

install:
  - curl -fsSL -O http://prdownloads.sourceforge.net/scons/scons-local-2.5.1.zip
  - 7z x scons-local-2.5.1.zip -oscons

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
  - python scons/scons.py platform=windows tools=yes target=release_debug verbose=no warnings=no
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x86
  - python scons/scons.py platform=windows tools=yes target=release_debug verbose=no warnings=no

after_build:
  - 7z a godot-windows-x86_64-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\godot.windows.opt.tools.64.exe
  - 7z a godot-windows-x86-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\godot.windows.opt.tools.32.exe

artifacts:
  - path: '*.zip'

deploy:
  - provider: FTP
    protocol: sftp
    host: hugo.pro
    username: godot
    password:
      secure: wPzpdQRz589GAsHPwAXMTgLsUrDB2+n2m2dKvV6Wihc=
    folder: autobuild/{build}
    application:
    active_mode: false
    debug: true
