image: Visual Studio 2017
shallow_clone: true

init:
 - ps: Update-AppveyorBuild -Version "$(Get-Date $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -format yyyy-MM-dd).$($env:APPVEYOR_REPO_COMMIT.substring(0, 7))"

install:
  - pip install --egg scons # `--egg` is required for use with AppVeyor

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
  - scons platform=windows tools=yes target=release_debug verbose=no warnings=no
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x86
  - scons platform=windows tools=yes target=release_debug verbose=no warnings=no

after_build:
  - mkdir %APPVEYOR_BUILD_VERSION%
  - 7z a %APPVEYOR_BUILD_VERSION%\Godot-Windows-x86_64-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\godot.windows.opt.tools.64.exe
  - 7z a %APPVEYOR_BUILD_VERSION%\Godot-Windows-x86-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\godot.windows.opt.tools.32.exe
  - git clone https://github.com/tomuxmon/godot.msi
  - cd godot.msi
  - copy /Y ..\platform\windows\godot.ico godot.ico
  - copy /Y ..\bin\godot.windows.opt.tools.64.exe godot.exe
  - call "%WIX%\bin\candle.exe" godot.wxs -dexe_path=godot.exe -dversion=3.0.0.0
  - call "%WIX%\bin\light.exe" godot.wixobj
  - move godot.msi ..\%APPVEYOR_BUILD_VERSION%\Godot-Windows-x86_64-%APPVEYOR_BUILD_VERSION%.msi
  - copy /Y ..\bin\godot.windows.opt.tools.32.exe godot.exe
  - call "%WIX%\bin\candle.exe" godot.wxs -dexe_path=godot.exe -dversion=3.0.0.0
  - call "%WIX%\bin\light.exe" godot.wixobj
  - move godot.msi ..\%APPVEYOR_BUILD_VERSION%\Godot-Windows-x86-%APPVEYOR_BUILD_VERSION%.msi

artifacts:
  - path: '**\*.zip'
  - path: '**\*.msi'

deploy:
  - provider: BinTray
    username: calinou
    api_key:
      secure: GJf+DF+dDdNyHsFP01JqBDaVUTI6jQ7VtDrDVp1S7vD94kT8/AbSOZSxIXyb7MBr
    subject: calinou
    repo: godot
    package: editor
    publish: true
    override: true
