---
# The GitHub repository is mirrored to GitLab.com daily, where continuous builds
# are performed and can be downloaded.
#
# https://gitlab.com/godotengine/godot
# Pipelines URL: https://gitlab.com/godotengine/godot/pipelines

stages:
  - build
  - package
  - deploy

build:linux:
  stage: build
  image: ubuntu:trusty
  before_script:
    - apt-get update -y
    - apt-get install -y build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libfreetype6-dev libssl-dev libudev-dev libxrandr-dev
  script:
    - scons platform=x11 tools=yes target=release_debug builtin_openssl=yes builtin_libpng=yes verbose=no warnings=no -j$(nproc)
    - strip bin/godot.x11.opt.tools.64
  artifacts:
    when: on_success
    expire_in: 2h
    paths:
      - bin/

package:linux:
  stage: package
  image: ubuntu:trusty
  dependencies:
    - build:linux
  before_script:
    - apt-get update -y
    - apt-get install -y wget build-essential pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libfreetype6-dev libssl-dev libudev-dev libxrandr-dev libglib2.0-0
  script:
    - mkdir -p appdir/usr/bin/ appdir/usr/share/icons
    - cp bin/godot.x11.opt.tools.64 appdir/usr/bin/godot
    - cp misc/dist/appimage/godot.desktop appdir/godot.desktop
    - cp icon.svg appdir/usr/share/icons/godot.svg
    - wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
    - chmod +x linuxdeployqt-continuous-x86_64.AppImage
    - ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
    - ./squashfs-root/AppRun appdir/godot.desktop -appimage
  artifacts:
    when: on_success
    expire_in: 2h
    paths:
      - Godot_Engine-x86_64.AppImage

deploy:linux:
  stage: deploy
  image: ubuntu:trusty
  dependencies:
    - package:linux
  before_script:
    - apt-get update -y
    - apt-get install -y git wget ruby rpl
    - gem install dpl
  script:
    - wget -q https://gist.githubusercontent.com/Calinou/894db8a79d1b606f5c9d08d01ba2cbbf/raw/.bintray.json -O .bintray.json
    - rpl '${VERSION}' "$(date +%Y-%m-%d).$(git rev-parse --short HEAD | head -c 7)" .bintray.json
    - rpl '${DATE}' "$(date +%Y-%m-%d)" .bintray.json
    - dpl --provider=bintray --file=.bintray.json --user=Calinou --key=$BINTRAY_API_KEY
