language: cpp

sudo: false

cache: ccache

compiler:
  - gcc
  - clang

os:
  - osx

env:
  global:
    - OPTIONS="verbose=no warnings=no progress=no builtin_openssl=yes -j$(sysctl -n hw.logicalcpu)"
  matrix:
    - PLATFORM=osx    INCLUDE_PATTERN_1="bin/Godot-macOS-x86_64.dmg"    UPLOAD_PATTERN_1="Godot-macOS-x86_64-#[VERSION].dmg"
                      INCLUDE_PATTERN_2="bin/Godot-Templates-macOS.tpz" UPLOAD_PATTERN_2="templates/Godot-Templates-macOS-#[VERSION].tpz"
    - PLATFORM=iphone INCLUDE_PATTERN="bin/Godot-Templates-iOS.tpz" UPLOAD_PATTERN="templates/Godot-Templates-iOS-#[VERSION].tpz"

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update; brew install scons ccache;
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$GODOT_TARGET" = "android" ]; then
      brew update; brew install -v android-sdk;
      brew install -v android-ndk | grep -v "inflating:" | grep -v "creating:";
      export ANDROID_HOME=/usr/local/opt/android-sdk; export ANDROID_NDK_ROOT=/usr/local/opt/android-ndk;
    fi

# For macOS, pretend 64-bit templates to be fat binaries, just in case
script:
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      sh ./misc/travis/clang-format.sh;
    else
      scons -j 2 platform=$GODOT_TARGET progress=no verbose=yes CXX=$CXX;
    fi
