language: cpp

sudo: false

cache: ccache

compiler:
  - gcc
  - clang

os:
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update; brew install scons ccache;
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$GODOT_TARGET" = "android" ]; then
      brew update; brew install -v android-sdk;
      brew install -v android-ndk | grep -v "inflating:" | grep -v "creating:";
      export ANDROID_HOME=/usr/local/opt/android-sdk; export ANDROID_NDK_ROOT=/usr/local/opt/android-ndk;
    fi

script:
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      sh ./misc/travis/clang-format.sh;
    else
      scons -j 2 platform=$GODOT_TARGET progress=no verbose=yes CXX=$CXX;
    fi
