# =====
# FIXME: Replace 'push' with 'schedule' in `if` conditions before opening a pull request!
# =====
name: 🍎 macOS Builds
on:
  push:
  pull_request:
  schedule:
    # Every day at midnight (UTC).
    # This keeps the class reference status page fresh.
    - cron: '0 0 * * *'

# Global Settings
env:
  GODOT_BASE_BRANCH: 3.2
  SCONSFLAGS: platform=osx verbose=yes warnings=all werror=yes --jobs=2
  SCONS_CACHE_LIMIT: 4096

jobs:
  macos-editor:
    runs-on: macos-10.15

    name: Editor (tools=yes)

    steps:
      - uses: actions/checkout@v2

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        # Don't use cache for optimized builds.
        if: github.event_name != 'push'
        id: macos-editor-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

      # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      # We should always be explicit with our flags usage here since it's gonna be sure to always set those flags
      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            unset SCONS_CACHE
            scons tools=yes target=release_debug debug_symbols=no
          else
            scons tools=yes target=debug
          fi
          ls -l bin/

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}-${{ github.event_name == 'push' && 'release' || 'debug' }}
          path: bin/*
          retention-days: 14
          if-no-files-found: error

  macos-template:
    runs-on: macos-10.15
    name: Export template (tools=no)

    steps:
      - uses: actions/checkout@v2

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        # Don't use cache for optimized builds.
        if: github.event_name != 'push'
        id: macos-template-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # You can test your matrix by printing the current Python version
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            unset SCONS_CACHE
            scons tools=no target=release debug_symbols=no
          else
            scons tools=no target=debug
          fi
          ls -l bin/

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}-${{ github.event_name == 'push' && 'release' || 'debug' }}
          path: bin/*
          retention-days: 14
          if-no-files-found: error
