# =====
# FIXME: Replace 'push' with 'schedule' in `if` conditions before opening a pull request!
# =====
name: 🏁 Windows Builds
on:
  push:
  pull_request:
  schedule:
    # Every day at midnight (UTC).
    # This schedule is used to compile fully optimized builds every day.
    - cron: '0 0 * * *'

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  GODOT_BASE_BRANCH: 3.2
  SCONSFLAGS: platform=windows verbose=yes warnings=all werror=yes --jobs=2
  SCONS_CACHE_MSVC_CONFIG: true
  SCONS_CACHE_LIMIT: 4096

jobs:
  windows-editor:
    # Windows 10 with latest image
    runs-on: windows-2019

    # Windows Editor - checkout with the plugin
    name: Editor (tools=yes)

    steps:
    - uses: actions/checkout@v2

      # Upload cache on completion and check it out now
      # Editing this is pretty dangerous for Windows since it can break and needs to be properly tested with a fresh cache.
    - name: Load .scons_cache directory
      # Don't use cache for optimized builds.
      if: github.event_name != 'push'
      id: windows-editor-cache
      uses: RevoluPowered/cache@v2.1
      with:
        path: /.scons_cache/
        key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

    # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'

    # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons pywin32
        python --version
        scons --version

    # We should always be explicit with our flags usage here since it's gonna be sure to always set those flags
    - name: Compilation
      env:
        SCONS_CACHE: /.scons_cache/
      run: |
        If ($env:GITHUB_EVENT_NAME -eq "push") {
          $env:SCONS_CACHE = $null
          scons tools=yes target=release_debug use_lto=yes debug_symbols=no
        } Else {
          scons tools=yes target=debug
        }
        ls -l bin/

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}-${{ github.event_name == 'push' && 'release' || 'debug' }}
        path: bin/*
        retention-days: 14
        if-no-files-found: error

  windows-template:
    runs-on: windows-2019
    name: Export template (tools=no)

    steps:
    - uses: actions/checkout@v2

    # Upload cache on completion and check it out now
    # Editing this is pretty dangerous for Windows since it can break and needs to be properly tested with a fresh cache.
    - name: Load .scons_cache directory
      # Don't use cache for optimized builds.
      if: github.event_name != 'push'
      id: windows-template-cache
      uses: RevoluPowered/cache@v2.1
      with:
        path: /.scons_cache/
        key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

    # Use python 3.x release (works cross platform)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'

    # You can test your matrix by printing the current Python version
    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons pywin32
        python --version
        scons --version

    - name: Compilation
      env:
        SCONS_CACHE: /.scons_cache/
      run: |
        If ($env:GITHUB_EVENT_NAME -eq "push") {
          $env:SCONS_CACHE = $null
          scons tools=no target=release target=release use_lto=yes debug_symbols=no
        } Else {
          scons tools=no target=debug
        }
        ls -l bin/

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}-${{ github.event_name == 'push' && 'release' || 'debug' }}
        path: bin/*
        retention-days: 14
        if-no-files-found: error
